### ISSUE TITLE
Error reading json

### ISSUE THREAD

**Issue by xhit** [tamerh/jsparser#3]
The commit b193e55 brokes the package.

This simple json return a panic:
```json
{"list":[
                    {"Name": "Ed", "Text": "Knock knock."},
                    {"Name": "Sam", "Text": "Who's there?"},
                    {"Name": "Ed", "Text": "Go fmt."},
                    {"Name": "Sam", "Text": "Go fmt who?"},
                    {"Name": "Ed", "Text": "Go fmt yourself!"}
                ]}
```

The error:
```
github.com/tamerh/jsparser.(*JsonParser).parse(0xc0000b50c0)
        C:/Users/sdelacruz/Documents/go/src/github.com/tamerh/jsparser/jsparser.go:156 +0x24c
created by github.com/tamerh/jsparser.(*JsonParser).Stream
        C:/Users/sdelacruz/Documents/go/src/github.com/tamerh/jsparser/jsparser.go:69 +0x46
```

Before this commit, the package works fine, but issue #1 is present.

**Comment by tamerh** [comment]
It should work now. Tests didn't catch this case so new test added as well. 

you have still issue #1? what is your json? I tested with the one you gave at #2 and it is producing the Err.

**Comment by xhit** [comment]
Tested and working.

I tested issue #1 with invalid and this issue with valid  and works like a charm.

Issue #1 and pull request #2  was about `res` was nil and check `Err` issued a panic with invalid json

This issue #3 issued a panic with valid json. Now is fixed.

Thanks.

**Comment by tamerh** [comment]
Great that it works now. Thanks
