### ISSUE TITLE
What is the proper way to read an array?

### ISSUE THREAD

**Issue by leechdraw** [tamerh/jsparser#6]
Hi!
I'm trying to read next kind of json file:
`
[
{"prop1":"val1", "prop2":"val2"},
{"prop1":"val1", "prop2":"val2"},
....
]
`

But it looks like there is no direct way to do it.

I found workaround - pack all file data into single object like:
`
{ "dummy_prop":
[
{"prop1":"val1", "prop2":"val2"},
{"prop1":"val1", "prop2":"val2"},
....
]
}
`

But it looks not good. Is there any other way to do it with jsparser?

**Comment by tamerh** [comment]
Hi, right now property is required but I will have a look to add this feature.

**Comment by tamerh** [comment]
I added this option now. If you want to try just pass empty loop property name `NewJSONParser(br, "")`
