### ISSUE TITLE
Non strict mode

### ISSUE THREAD

**Issue by 89z** [tamerh/jsparser#7]
I am trying to parse JSON from some input like this:

~~~js
window.__additionalDataLoaded('extra',{"shortcode_media":999});
~~~

Where the output would be:

~~~json
{"shortcode_media":999}
~~~

is something like that possible? Similar to `Strict = false` with XML:

https://godocs.io/encoding/xml#Decoder.Strict

**Comment by tamerh** [comment]
Obviously your input is not a JSON text but library can still try to parse as it is stream based parser primarily for large inputs. Not sure about your real input but in this case you can still parse the value of `shortcode_media` even you have multiple lines of same input by `jsparser.NewJSONParser(br, "shortcode_media")`

**Comment by 89z** [comment]
Thank you for the comment! What if input has two keys?

~~~js
window.__additionalDataLoaded('extra',{"hello":999,"world":888});
~~~

can I iterate over all keys?
